#!/usr/bin/env bash
#
# deploy.sh — generate ~/.claude/CLAUDE.md from this repo.
#
# Composes Claude Code's global user memory from one or two @import lines:
#   1. the shared rules core (rules.md)
#   2. this machine's overlay (machines/<hostname>.md), if present
#
# Idempotent: re-running just rewrites the generated file.
#
set -euo pipefail

CLAUDE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOST="$(hostname -s)"
MACHINE_FILE="$CLAUDE_DIR/machines/${HOST}.md"
TARGET="$HOME/.claude/CLAUDE.md"

if [ ! -f "$CLAUDE_DIR/rules.md" ]; then
  echo "!! Missing $CLAUDE_DIR/rules.md" >&2
  exit 1
fi

mkdir -p "$HOME/.claude"

# Back up any pre-existing hand-written CLAUDE.md (not one we generated).
if [ -f "$TARGET" ] && ! grep -q "Generated by .*deploy.sh" "$TARGET" 2>/dev/null; then
  backup="${TARGET}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$TARGET" "$backup"
  echo ">> backed up existing $TARGET -> $backup"
fi

{
  echo "<!-- Generated by deploy.sh — do NOT edit by hand. -->"
  echo "<!-- Edit rules.md (and machines/${HOST}.md, if present) instead. -->"
  echo
  echo "@$CLAUDE_DIR/rules.md"
  if [ -f "$MACHINE_FILE" ]; then
    echo "@$MACHINE_FILE"
  fi
} > "$TARGET"

echo ">> wrote $TARGET (host '$HOST')"
if [ -f "$MACHINE_FILE" ]; then
  echo "   imports: rules.md + machines/${HOST}.md"
else
  echo "   imports: rules.md only (no machines/${HOST}.md found — see machines/example.md to add one)"
fi
