#!/usr/bin/env bash
#
# deploy.sh — generate ~/.claude/CLAUDE.md from this repo.
#
# Composes Claude Code's global user memory from @import lines, in this order:
#   1. the shared rules core (rules.md)
#   2. any extra files given with --import, in the order given
#   3. this machine's overlay (<machines-dir>/<hostname>.md), if present
#
# This is the ONLY generator: a private repo that layers its own addendum and
# machine overlays on top should call this script with the flags below rather
# than keep its own copy (two copies drift apart).
#
# Usage: deploy.sh [--machines-dir <dir>] [--import <file>]... [--require-machine] [--harnesses]
#   --machines-dir <dir>  where to look for <hostname>.md (default: <this dir>/machines)
#   --import <file>       repeatable; extra @import placed after rules.md, before the
#                         machine overlay. A missing file is an error.
#   --require-machine     missing machine overlay is an error (default: skip it)
#   --harnesses           ALSO write a flat copy (rules.md + --import files + machine
#                         overlay concatenated, no @imports) to the global instructions
#                         file of every other coding harness found on PATH or in the standard
#                         install dirs (HARNESS_BIN_DIRS, so cron's minimal PATH works) — see the
#                         harness_targets() table below. Default off.
#
# Why flat: only Claude Code resolves @imports in a global file; Codex, OpenCode etc.
# would see the literal "@~/..." lines (or, for Copilot, skip the import).
#
# Idempotent: re-running just rewrites the generated file(s); flat copies are left
# untouched (byte-identical, no new backup) when their content has not changed.
#
# Must run on macOS bash 3.2: no associative arrays, and "${arr[@]}" on an empty
# array is an error under `set -u`, so the array is only expanded behind a count check.
#
set -euo pipefail

CLAUDE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOST="$(hostname -s)"
MACHINES_DIR="$CLAUDE_DIR/machines"
REQUIRE_MACHINE=0
IMPORTS=()
TARGET="$HOME/.claude/CLAUDE.md"
HARNESSES=0

usage() {
  echo "usage: deploy.sh [--machines-dir <dir>] [--import <file>]... [--require-machine] [--harnesses]" >&2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --machines-dir)
      [ $# -ge 2 ] || { echo "!! --machines-dir needs a value" >&2; usage; exit 1; }
      MACHINES_DIR="$2"; shift 2 ;;
    --import)
      [ $# -ge 2 ] || { echo "!! --import needs a value" >&2; usage; exit 1; }
      IMPORTS+=("$2"); shift 2 ;;
    --require-machine)
      REQUIRE_MACHINE=1; shift ;;
    --harnesses)
      HARNESSES=1; shift ;;
    *)
      echo "!! Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

MACHINE_FILE="$MACHINES_DIR/${HOST}.md"

# Collapse a leading $HOME to ~ — Claude Code resolves ~ in @imports, and it keeps
# the generated file identical across machines with different home paths.
tilde() {
  # shellcheck disable=SC2088  # literal ~ is intended: Claude Code expands it at load time
  case "$1" in
    "$HOME"/*) printf '~/%s' "${1#"$HOME"/}" ;;
    *)         printf '%s' "$1" ;;
  esac
}

if [ ! -f "$CLAUDE_DIR/rules.md" ]; then
  echo "!! Missing $CLAUDE_DIR/rules.md" >&2
  exit 1
fi

# Validate every --import up front so a typo never leaves a half-written target.
if [ "${#IMPORTS[@]}" -gt 0 ]; then
  for f in "${IMPORTS[@]}"; do
    if [ ! -f "$f" ]; then
      echo "!! Missing import file: $f" >&2
      exit 1
    fi
  done
fi

if [ "$REQUIRE_MACHINE" -eq 1 ] && [ ! -f "$MACHINE_FILE" ]; then
  echo "!! No machine file for host '$HOST': $MACHINE_FILE" >&2
  echo "   Create it (see machines/example.md as a template), then re-run." >&2
  exit 1
fi

mkdir -p "$HOME/.claude"

# Back up any pre-existing hand-written CLAUDE.md (not one we generated).
if [ -f "$TARGET" ] && ! grep -q "Generated by .*deploy.sh" "$TARGET" 2>/dev/null; then
  backup="${TARGET}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$TARGET" "$backup"
  echo ">> backed up existing $TARGET -> $backup"
fi

{
  echo "<!-- Generated by deploy.sh — do NOT edit by hand. -->"
  echo "<!-- Edit the imported files instead:                -->"
  echo "<!--   rules : $(tilde "$CLAUDE_DIR/rules.md") -->"
  if [ "${#IMPORTS[@]}" -gt 0 ]; then
    for f in "${IMPORTS[@]}"; do
      echo "<!--   import: $(tilde "$f") -->"
    done
  fi
  if [ -f "$MACHINE_FILE" ]; then
    echo "<!--   machine: $(tilde "$MACHINE_FILE") -->"
  fi
  echo
  echo "@$(tilde "$CLAUDE_DIR/rules.md")"
  if [ "${#IMPORTS[@]}" -gt 0 ]; then
    for f in "${IMPORTS[@]}"; do
      echo "@$(tilde "$f")"
    done
  fi
  if [ -f "$MACHINE_FILE" ]; then
    echo "@$(tilde "$MACHINE_FILE")"
  fi
} > "$TARGET"

echo ">> wrote $TARGET (host '$HOST')"
summary="rules.md"
if [ "${#IMPORTS[@]}" -gt 0 ]; then
  for f in "${IMPORTS[@]}"; do
    summary="$summary + $(basename "$f")"
  done
fi
if [ -f "$MACHINE_FILE" ]; then
  echo "   imports: $summary + machines/${HOST}.md"
else
  echo "   imports: $summary (no ${HOST}.md in $MACHINES_DIR — see machines/example.md to add one)"
fi

# ---------------------------------------------------------------------------
# --harnesses: flat copies for every other coding harness.
# ---------------------------------------------------------------------------
[ "$HARNESSES" -eq 1 ] || exit 0

# THE target table — the one place that knows where each harness reads its global
# instructions. One row per file written, one path per harness (so no harness loads
# the same content twice).
#   row:  <binaries, space-separated> | <target path> | <when>
#   when: "if-bin"  write only if one of the binaries is on PATH or in HARNESS_BIN_DIRS (below)
#         "always"  write regardless (see opencode)
# Rows are unquoted-heredoc lines, so $HOME / ${VAR:-default} expand; '#' lines are
# comments. Doc sources are in the comments (checked 2026-10-09).
#
# Not generated: Cursor (User Rules are GUI-only), Copilot on github.com (personal-
# instructions text box), Windsurf (6,000-char global cap), Aider (no global instructions
# file), Cline (manual); Gemini CLI (deprecated upstream, superseded by Antigravity),
# Amp and Crush (not supported, by choice).
harness_targets() {
  cat <<TABLE
# codex: ~/.codex/AGENTS.md (\$CODEX_HOME relocates it).
#   docs: learn.chatgpt.com/docs/agent-configuration/agents-md ; source: openai/codex codex-rs/codex-home/src/instructions/mod.rs
codex|${CODEX_HOME:-$HOME/.codex}/AGENTS.md|if-bin
# agy (Antigravity CLI): ~/.gemini/AGENTS.md. Its global rules are ~/.gemini/AGENTS.md and
# ~/.gemini/GEMINI.md (plus ~/.gemini/config/ copies and rules/*.md); only one is written,
# else both files load (rules are cumulative). AGENTS.md is the name its docs recommend, and GEMINI.md is
# also written by Gemini CLI and the Antigravity IDE. Rule files are capped at 24,000
# bytes after expanding includes, truncated on line boundaries.
#   docs: antigravity.google/docs/rules (section "Managing rules in Antigravity CLI") ;
#   also embedded in the agy binary (Homebrew cask antigravity-cli 1.3.2): its rules doc
#   text, per-file limit text and CHANGELOG entry on ~/.gemini/{GEMINI,AGENTS}.md.
agy|$HOME/.gemini/AGENTS.md|if-bin
# opencode: ~/.config/opencode/AGENTS.md. ALWAYS written: with no file here OpenCode falls
# back to ~/.claude/CLAUDE.md and injects its literal @import lines as instructions.
#   docs: opencode.ai/docs/rules ; source: sst/opencode packages/opencode/src/session/instruction.ts
opencode|$HOME/.config/opencode/AGENTS.md|always
# copilot (CLI): ~/.copilot/copilot-instructions.md (\$COPILOT_HOME relocates it).
#   docs: github/docs content/copilot/how-tos/copilot-cli/customize-copilot/add-custom-instructions.md
copilot|${COPILOT_HOME:-$HOME/.copilot}/copilot-instructions.md|if-bin
# goose: ~/.config/goose/AGENTS.md (it also reads ~/.agents/AGENTS.md; only one is written).
#   docs: goose-docs.ai/docs/guides/context-engineering/using-goosehints ; source: block/goose crates/goose/src/hints/load_hints.rs
goose|$HOME/.config/goose/AGENTS.md|if-bin
TABLE
}

# Render the flat file to stdout: generated-by header (the backup guard below relies
# on it), then each source in the same order as the @imports above — rules.md, the
# --import files, the machine overlay — each behind a marker naming its source.
render_flat() {
  echo "<!-- Generated by deploy.sh — do NOT edit by hand. -->"
  echo "<!-- Flat copy for non-Claude harnesses; Claude Code uses @imports instead. -->"
  echo "<!-- Edit the source files named below, then re-run deploy.sh --harnesses. -->"
  flat_part "$CLAUDE_DIR/rules.md"
  if [ "${#IMPORTS[@]}" -gt 0 ]; then
    for f in "${IMPORTS[@]}"; do
      flat_part "$f"
    done
  fi
  if [ -f "$MACHINE_FILE" ]; then
    flat_part "$MACHINE_FILE"
  fi
}

# One source: blank line, marker, content (newline-terminated even if the file isn't).
flat_part() {
  echo
  echo "<!-- source: $(tilde "$1") -->"
  cat "$1"
  if [ -n "$(tail -c1 "$1")" ]; then echo; fi
}

# Build the flat file once; every target gets a copy of it. Temp file is mode 600
# (mktemp default) because the content can include a private layer.
FLAT_TMP="$(mktemp "${TMPDIR:-/tmp}/deploy-flat.XXXXXX")"
trap 'rm -f "$FLAT_TMP"' EXIT
render_flat > "$FLAT_TMP"

# Where harness binaries land that a minimal PATH (cron: /usr/bin:/bin) does not cover.
# Probe-only: PATH is never changed, so nothing else in this run sees these dirs.
#   Homebrew (Apple Silicon, Intel/Linux prefix), ~/.local/bin (vendor installers and
#   release-binary installs), ~/.opencode/bin (OpenCode's own installer), npm global
#   prefix (~/.npm-global), mise shims.
HARNESS_BIN_DIRS="/opt/homebrew/bin /usr/local/bin $HOME/.local/bin $HOME/.opencode/bin $HOME/.npm-global/bin $HOME/.local/share/mise/shims"

# bin_present <name>: true if on PATH or executable in one of HARNESS_BIN_DIRS.
bin_present() {
  command -v "$1" >/dev/null 2>&1 && return 0
  local d
  for d in $HARNESS_BIN_DIRS; do
    [ -x "$d/$1" ] && [ ! -d "$d/$1" ] && return 0
  done
  return 1
}

written=0
while IFS='|' read -r bins path when; do
  case "$bins" in ''|'#'*) continue ;; esac

  present=""
  for b in $bins; do
    if bin_present "$b"; then present="$b"; break; fi
  done
  if [ -z "$present" ] && [ "$when" != "always" ]; then
    echo ">> skip $path ($bins not on PATH or in the standard install dirs)"
    continue
  fi

  # A shared path appears once in the table, so no duplicate-write guard is needed.
  mkdir -p "$(dirname "$path")"

  # Same guard as ~/.claude/CLAUDE.md: back up a hand-written file, never a generated one.
  if [ -f "$path" ] && ! grep -q "Generated by .*deploy.sh" "$path" 2>/dev/null; then
    backup="${path}.bak.$(date +%Y%m%d%H%M%S)"
    cp "$path" "$backup"
    echo ">> backed up existing $path -> $backup"
  fi

  if [ -f "$path" ] && cmp -s "$FLAT_TMP" "$path"; then
    chmod 600 "$path"
    echo ">> unchanged $path"
  else
    # Temp file in the target's own dir + mv = atomic replace; a failed run never
    # leaves a half-written instructions file. umask 077 keeps the temp private.
    part="${path}.tmp.$$"
    ( umask 077; cp "$FLAT_TMP" "$part" )
    chmod 600 "$part"
    mv "$part" "$path"
    echo ">> wrote $path"
  fi
  written=$((written + 1))
done <<EOF
$(harness_targets)
EOF
echo "   flat copies: $written target(s) up to date"
