#!/usr/bin/env bash
#
# deploy.sh — generate ~/.claude/CLAUDE.md from this repo.
#
# Composes Claude Code's global user memory from @import lines, in this order:
#   1. the shared rules core (rules.md)
#   2. any extra files given with --import, in the order given
#   3. this machine's overlay (<machines-dir>/<hostname>.md), if present
#
# This is the ONLY generator: a private repo that layers its own addendum and
# machine overlays on top should call this script with the flags below rather
# than keep its own copy (two copies drift apart).
#
# Usage: deploy.sh [--machines-dir <dir>] [--import <file>]... [--require-machine]
#   --machines-dir <dir>  where to look for <hostname>.md (default: <this dir>/machines)
#   --import <file>       repeatable; extra @import placed after rules.md, before the
#                         machine overlay. A missing file is an error.
#   --require-machine     missing machine overlay is an error (default: skip it)
#
# Idempotent: re-running just rewrites the generated file.
#
# Must run on macOS bash 3.2: no associative arrays, and "${arr[@]}" on an empty
# array is an error under `set -u`, so the array is only expanded behind a count check.
#
set -euo pipefail

CLAUDE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOST="$(hostname -s)"
MACHINES_DIR="$CLAUDE_DIR/machines"
REQUIRE_MACHINE=0
IMPORTS=()
TARGET="$HOME/.claude/CLAUDE.md"

usage() {
  echo "usage: deploy.sh [--machines-dir <dir>] [--import <file>]... [--require-machine]" >&2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --machines-dir)
      [ $# -ge 2 ] || { echo "!! --machines-dir needs a value" >&2; usage; exit 1; }
      MACHINES_DIR="$2"; shift 2 ;;
    --import)
      [ $# -ge 2 ] || { echo "!! --import needs a value" >&2; usage; exit 1; }
      IMPORTS+=("$2"); shift 2 ;;
    --require-machine)
      REQUIRE_MACHINE=1; shift ;;
    *)
      echo "!! Unknown argument: $1" >&2; usage; exit 1 ;;
  esac
done

MACHINE_FILE="$MACHINES_DIR/${HOST}.md"

# Collapse a leading $HOME to ~ — Claude Code resolves ~ in @imports, and it keeps
# the generated file identical across machines with different home paths.
tilde() {
  # shellcheck disable=SC2088  # literal ~ is intended: Claude Code expands it at load time
  case "$1" in
    "$HOME"/*) printf '~/%s' "${1#"$HOME"/}" ;;
    *)         printf '%s' "$1" ;;
  esac
}

if [ ! -f "$CLAUDE_DIR/rules.md" ]; then
  echo "!! Missing $CLAUDE_DIR/rules.md" >&2
  exit 1
fi

# Validate every --import up front so a typo never leaves a half-written target.
if [ "${#IMPORTS[@]}" -gt 0 ]; then
  for f in "${IMPORTS[@]}"; do
    if [ ! -f "$f" ]; then
      echo "!! Missing import file: $f" >&2
      exit 1
    fi
  done
fi

if [ "$REQUIRE_MACHINE" -eq 1 ] && [ ! -f "$MACHINE_FILE" ]; then
  echo "!! No machine file for host '$HOST': $MACHINE_FILE" >&2
  echo "   Create it (see machines/example.md as a template), then re-run." >&2
  exit 1
fi

mkdir -p "$HOME/.claude"

# Back up any pre-existing hand-written CLAUDE.md (not one we generated).
if [ -f "$TARGET" ] && ! grep -q "Generated by .*deploy.sh" "$TARGET" 2>/dev/null; then
  backup="${TARGET}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$TARGET" "$backup"
  echo ">> backed up existing $TARGET -> $backup"
fi

{
  echo "<!-- Generated by deploy.sh — do NOT edit by hand. -->"
  echo "<!-- Edit the imported files instead:                -->"
  echo "<!--   rules : $(tilde "$CLAUDE_DIR/rules.md") -->"
  if [ "${#IMPORTS[@]}" -gt 0 ]; then
    for f in "${IMPORTS[@]}"; do
      echo "<!--   import: $(tilde "$f") -->"
    done
  fi
  if [ -f "$MACHINE_FILE" ]; then
    echo "<!--   machine: $(tilde "$MACHINE_FILE") -->"
  fi
  echo
  echo "@$(tilde "$CLAUDE_DIR/rules.md")"
  if [ "${#IMPORTS[@]}" -gt 0 ]; then
    for f in "${IMPORTS[@]}"; do
      echo "@$(tilde "$f")"
    done
  fi
  if [ -f "$MACHINE_FILE" ]; then
    echo "@$(tilde "$MACHINE_FILE")"
  fi
} > "$TARGET"

echo ">> wrote $TARGET (host '$HOST')"
summary="rules.md"
if [ "${#IMPORTS[@]}" -gt 0 ]; then
  for f in "${IMPORTS[@]}"; do
    summary="$summary + $(basename "$f")"
  done
fi
if [ -f "$MACHINE_FILE" ]; then
  echo "   imports: $summary + machines/${HOST}.md"
else
  echo "   imports: $summary (no ${HOST}.md in $MACHINES_DIR — see machines/example.md to add one)"
fi
